{
  File generated by GameHelper, tool provided with OGLCScene library.

  DON'T EDIT THIS UNIT because it may be overwritten by the tool -> your code will be lost !
  Instead, in another unit add "u_panel_basemain" in the uses clause
  and add your code in a class inherited from TPanelBaseMain.

  Usage:
    - create an instance of the panel
      i.e. FBaseMain := TCustomBaseMain.Create(aLAYER_INDEX);
    or if the panel is a child of another surface:
           FBaseMain := TCustomBaseMain.Create(-1);
           FBaseMain.SetChildOf(parentSurface, zordervalue);
    - initialize the panel coordinates
           FBaseMain.Setcoordinates(...);
}

unit u_panel_basemain;

{$mode ObjFPC}{$H+}

interface

uses
  Classes, SysUtils,
  OGLCScene, BGRABitmap, BGRABitmapTypes, u_common;

type

TPanelBaseMain = class(TUIPanelWithEffects)
public
  BPlay: TUIButton;
  BQuit: TUIButton;
  BOptions: TUIButton;
  constructor Create;
end;

implementation

{ TPanelBaseMain }

constructor TPanelBaseMain.Create;
begin
  inherited Create(FScene);
  SetCoordinate(ScaleWF(289.84), ScaleHF(798.82));
  BodyShape.LoadFromString('ShapeType,0,Width,293,Height,230,FillData,Visible false,BorderData,Visible false Color DCDCDCFF Width 3.0000 BlendMode 0 LinePos 1');
  BodyShape.ResizeCurrentShape(ScaleW(293), ScaleH(230), True);

  BPlay := TUIButton.Create(FScene);
  with BPlay do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.351*Self.Width, 0.078*Self.Height);
    _Label.Tint.Value := BGRA(255,255,0);
    InitParameters('PLAY', texturedfontMenu, NIL);
    BodyShape.LoadFromString('ShapeType,1,RoundX,30.0000,RoundY,30.0000,Width,95,Height,50,FillData,Visible true Color 1E1D06FF BlendMode 0,BorderData,Visible true Color DCDCDCFF Width 3.0000 BlendMode 0 LinePos 1');
    BodyShape.ResizeCurrentShape(ScaleW(95), ScaleH(50), True);
  end;

  BQuit := TUIButton.Create(FScene);
  with BQuit do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.345*Self.Width, 0.704*Self.Height);
    _Label.Tint.Value := BGRA(255,255,0);
    InitParameters('QUIT', texturedfontMenu, NIL);
    BodyShape.LoadFromString('ShapeType,1,RoundX,30.0000,RoundY,30.0000,Width,150,Height,50,FillData,Color 1E1E1EFF BlendMode 0,BorderData,Color DCDCDCFF Width 3.0000 BlendMode 0 LinePos 1');
    BodyShape.ResizeCurrentShape(ScaleW(93), ScaleH(50), True);
  end;

  BOptions := TUIButton.Create(FScene);
  with BOptions do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.257*Self.Width, 0.391*Self.Height);
    Pivot := PointF(0.50, 0.50);
    _Label.Tint.Value := BGRA(255,255,0);
    InitParameters('OPTIONS', texturedfontMenu, NIL);
    BodyShape.LoadFromString('ShapeType,1,RoundX,30.0000,RoundY,30.0000,Width,156,Height,50,FillData,Visible true Color 1E1E1EFF BlendMode 0,BorderData,Visible true Color DCDCDCFF Width 3.0000 BlendMode 0 LinePos 1');
    BodyShape.ResizeCurrentShape(ScaleW(156), ScaleH(50), True);
  end;
end;

end.
