{
  File generated by GameHelper, tool provided with OGLCScene library.

  DON'T EDIT THIS UNIT because it may be overwritten by the tool -> your code will be lost !
  Instead, in another unit add "u_sprite_title" in the uses clause
  and add your code in a class inherited from TTitle.

  Usage:
    - create an instance of the sprite
      i.e. FTitle := TCustomTitle.Create(aLAYER_INDEX);
    or if the sprite is a child of another:
           FTitle := TCustomTitle.Create(-1);
           FTitle.SetChildOf(parentSprite, zordervalue);
    - initialize the sprite coordinates
           FTitle.Setcoordinates(...);
}

unit u_sprite_title;

{$mode ObjFPC}{$H+}

interface

uses
  Classes, SysUtils,
  OGLCScene, BGRABitmap, BGRABitmapTypes, u_common;

type

TTitle = class(TFreeText)
public
  constructor Create(aLayerIndex: integer=-1);
end;

implementation

{ TTitle }

constructor TTitle.Create(aLayerIndex: integer);
begin
  inherited Create(FScene);
  if aLayerIndex <> -1 then
    FScene.Add(Self, aLayerIndex);
  SetCoordinate(ScaleWF(93.87), ScaleHF(21.33));
  Caption := 'PAC-MAN';
  TexturedFont := texturedfontTitle;


end;

end.
