{
  File generated by GameHelper, tool provided with OGLCScene library.

  DON'T EDIT THIS UNIT because it may be overwritten by the tool -> your code will be lost !
  Instead, in another unit add "u_sprite_labelhighscore" in the uses clause
  and add your code in a class inherited from TLabelHighScore.

  Usage:
    - create an instance of the sprite
      i.e. FLabelHighScore := TCustomLabelHighScore.Create(aLAYER_INDEX);
    or if the sprite is a child of another:
           FLabelHighScore := TCustomLabelHighScore.Create(-1);
           FLabelHighScore.SetChildOf(parentSprite, zordervalue);
    - initialize the sprite coordinates
           FLabelHighScore.Setcoordinates(...);
}

unit u_sprite_labelhighscore;

{$mode ObjFPC}{$H+}

interface

uses
  Classes, SysUtils,
  OGLCScene, BGRABitmap, BGRABitmapTypes, u_common;

type

TLabelHighScore = class(TFreeText)
public
  constructor Create(aLayerIndex: integer=-1);
end;

implementation

{ TLabelHighScore }

constructor TLabelHighScore.Create(aLayerIndex: integer);
begin
  inherited Create(FScene);
  if aLayerIndex <> -1 then
    FScene.Add(Self, aLayerIndex);
  Caption := 'HIGH SCORE';
  TexturedFont := texturedfontText;
end;

end.
