{
  File generated by GameHelper, tool provided with OGLCScene library.

  DON'T EDIT THIS UNIT because it may be overwritten by the tool -> your code will be lost !
  Instead, in another unit add "u_sprite_labelplayerone" in the uses clause
  and add your code in a class inherited from TLabelPlayerOne.

  Usage:
    - create an instance of the sprite
      i.e. FLabelPlayerOne := TCustomLabelPlayerOne.Create(aLAYER_INDEX);
    or if the sprite is a child of another:
           FLabelPlayerOne := TCustomLabelPlayerOne.Create(-1);
           FLabelPlayerOne.SetChildOf(parentSprite, zordervalue);
    - initialize the sprite coordinates
           FLabelPlayerOne.Setcoordinates(...);
}

unit u_sprite_labelplayerone;

{$mode ObjFPC}{$H+}

interface

uses
  Classes, SysUtils,
  OGLCScene, BGRABitmap, BGRABitmapTypes, u_common;

type

TLabelPlayerOne = class(TFreeText)
public
  constructor Create(aLayerIndex: integer=-1);
end;

implementation

{ TLabelPlayerOne }

constructor TLabelPlayerOne.Create(aLayerIndex: integer);
begin
  inherited Create(FScene);
  if aLayerIndex <> -1 then
    FScene.Add(Self, aLayerIndex);
  Tint.Value := BGRA(0,255,255);
  Caption := 'PLAYER ONE';
  TexturedFont := texturedfontText;


end;

end.
