{
  File generated by GameHelper, tool provided with OGLCScene library.

  DON'T EDIT THIS UNIT because it may be overwritten by the tool -> your code will be lost !
  Instead, in another unit add "u_panel_main" in the uses clause
  and add your code in a class inherited from TPanelMain.

  Usage:
    - create an instance of the panel
      i.e. FMain := TCustomMain.Create(aLAYER_INDEX);
    or if the panel is a child of another surface:
           FMain := TCustomMain.Create(-1);
           FMain.SetChildOf(parentSurface, zordervalue);
    - initialize the panel coordinates
           FMain.Setcoordinates(...);
}

unit u_panel_main;

{$mode ObjFPC}{$H+}

interface

uses
  Classes, SysUtils,
  OGLCScene, BGRABitmap, BGRABitmapTypes, u_common;

type

TPanelMain = class(TUIPanelWithEffects)
public
  Button1: TUIButton;
  BOptions: TUIButton;
  BQuit: TUIButton;
  constructor Create;
end;

implementation

{ TPanelMain }

constructor TPanelMain.Create;
begin
  inherited Create(FScene);
  SetCoordinate(ScaleWF(116.84), ScaleHF(469.33));
  BodyShape.LoadFromString('ShapeType,0,Width,309,Height,241,FillData,Visible false,BorderData,Visible false Color DCDCDCFF Width 3.0000 BlendMode 0 LinePos 1');
  BodyShape.ResizeCurrentShape(ScaleW(309), ScaleH(241), True);
  BackGradient.LoadGradientDataFromString('Visible false RowCount 0');
  BackGradient.ComputeVerticesAndIndices(ScaleW(309), ScaleH(241));
  ActivateSceneDarken(BGRA(0,0,0,100));

  Button1 := TUIButton.Create(FScene);
  with Button1 do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.336*Self.Width, 0.124*Self.Height);
    BodyShape.LoadFromString('ShapeType,1,RoundX,30.0000,RoundY,30.0000,Width,50,Height,24,FillData,Visible true Color 1E1D06FF BlendMode 0,BorderData,Visible true Color 918957FF Width 3.0000 BlendMode 0 LinePos 1');
    BodyShape.ResizeCurrentShape(ScaleW(98), ScaleH(45), True);
    BackGradient.LoadGradientDataFromString('Visible false RowCount 2 YPos0 0.0000 NodeCount0 2 R0_0XPos 0.0000 R0_0Color FFFF00FF R0_1XPos 1.0000 R0_1Color 00FFFFFF YPos1 1.0000 NodeCount1 2 R1_0XPos 0.0000 R1_0Color FFFF00FF R1_1XPos 1.0000 R1_1Color 00FFFFFF');
    BackGradient.ComputeVerticesAndIndices(ScaleW(98), ScaleH(45));
    InitParameters('PLAY', texturedfontMenu, NIL);
  end;

  BOptions := TUIButton.Create(FScene);
  with BOptions do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.239*Self.Width, 0.460*Self.Height);
    BodyShape.LoadFromString('ShapeType,1,RoundX,30.0000,RoundY,30.0000,Width,150,Height,50,FillData,Color 1E1E1EFF BlendMode 0,BorderData,Color DCDCDCFF Width 3.0000 BlendMode 0 LinePos 1');
    BodyShape.ResizeCurrentShape(ScaleW(159), ScaleH(45), True);
    InitParameters('OPTIONS', texturedfontMenu, NIL);
  end;

  BQuit := TUIButton.Create(FScene);
  with BQuit do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.327*Self.Width, 0.773*Self.Height);
    BodyShape.LoadFromString('ShapeType,1,RoundX,30.0000,RoundY,30.0000,Width,150,Height,50,FillData,Color 1E1E1EFF BlendMode 0,BorderData,Color DCDCDCFF Width 3.0000 BlendMode 0 LinePos 1');
    BodyShape.ResizeCurrentShape(ScaleW(107), ScaleH(45), True);
    InitParameters('QUIT', texturedfontMenu, NIL);
  end;
end;

end.
