{
  File generated by GameHelper, tool provided with OGLCScene library.

  DON'T EDIT THIS UNIT because it may be overwritten by the tool -> your code will be lost !
  Instead, in another unit add "u_sprite_ghostworm" in the uses clause
  and add your code in a class inherited from TGhostWorm.

  Usage:
    - add the sprite textures to your atlas with class method TGhostWorm.LoadTexture().
    - create an instance of the sprite
      i.e. FGhostWorm := TCustomGhostWorm.Create(aLAYER_INDEX);
    or if the sprite is a child of another:
           FGhostWorm := TCustomGhostWorm.Create(-1);
           FGhostWorm.SetChildOf(parentSprite, zordervalue);
    - initialize the sprite coordinates
           FGhostWorm.Setcoordinates(...);
}

unit u_sprite_ghostworm;

{$mode ObjFPC}{$H+}

interface

uses
  Classes, SysUtils,
  OGLCScene, BGRABitmap, BGRABitmapTypes, u_common;

type

TGhostWorm = class(TSprite)
private
  class var texGhostWorm: PTexture;
  class var FAdditionnalScale: single;
public
  class procedure LoadTexture(aAtlas: TOGLCTextureAtlas);
  constructor Create(aLayerIndex: integer=-1);
end;

implementation

{ TGhostWorm }

class procedure TGhostWorm.LoadTexture(aAtlas: TOGLCTextureAtlas);
var texFolder: string;
begin
  FAdditionnalScale := AdditionnalScale;
  texFolder := u_common.TexturesFolder;
  texGhostWorm := aAtlas.RetrieveTextureByFileName('GhostWorm.svg');
  if texGhostWorm = NIL then
    texGhostWorm := aAtlas.AddMultiFrameImageFromSVG(texFolder+'GhostWorm.svg', ScaleW(64)*2, ScaleH(64)*1, 2, 1);
end;

constructor TGhostWorm.Create(aLayerIndex: integer);
begin
  inherited Create(texGhostWorm, False);
  if aLayerIndex <> -1 then
    FScene.Add(Self, aLayerIndex);
  Frame := 1.0;
  SetSize(ScaleW(Round(64*FAdditionnalScale)), ScaleH(Round(64*FAdditionnalScale)));


end;

end.
