{
  File generated by GameHelper, tool provided with OGLCScene library.

  DON'T EDIT THIS UNIT because it may be overwritten by the tool -> your code will be lost !
  Instead, in another unit add "u_sprite_baselabelready" in the uses clause
  and add your code in a class inherited from TBaseLabelReady.

  Usage:
    - create an instance of the sprite
      i.e. FLabelReady := TCustomLabelReady.Create(aLAYER_INDEX);
    or if the sprite is a child of another:
           FLabelReady := TCustomLabelReady.Create(-1);
           FLabelReady.SetChildOf(parentSprite, zordervalue);
    - initialize the sprite coordinates
           FLabelReady.Setcoordinates(...);
}

unit u_sprite_baselabelready;

{$mode ObjFPC}{$H+}

interface

uses
  Classes, SysUtils,
  OGLCScene, BGRABitmap, BGRABitmapTypes, u_common;

type

TBaseLabelReady = class(TFreeText)
public
  constructor Create(aLayerIndex: integer=-1);
end;

implementation

{ TBaseLabelReady }

constructor TBaseLabelReady.Create(aLayerIndex: integer);
begin
  inherited Create(FScene);
  if aLayerIndex <> -1 then
    FScene.Add(Self, aLayerIndex);
  Tint.Value := BGRA(255,255,0);
  Caption := 'READY !';
  TexturedFont := texturedfontText;


end;

end.
