{
  File generated by GameHelper, tool provided with OGLCScene library.

  DON'T EDIT THIS UNIT because it may be overwritten by the tool -> your code will be lost !
  Instead, in another unit add "u_sprite_score" in the uses clause
  and add your code in a class inherited from TScore.

  Usage:
    - create an instance of the sprite
      i.e. FScore := TCustomScore.Create(aLAYER_INDEX);
    or if the sprite is a child of another:
           FScore := TCustomScore.Create(-1);
           FScore.SetChildOf(parentSprite, zordervalue);
    - initialize the sprite coordinates
           FScore.Setcoordinates(...);
}

unit u_sprite_score;

{$mode ObjFPC}{$H+}

interface

uses
  Classes, SysUtils,
  OGLCScene, BGRABitmap, BGRABitmapTypes, u_common;

type

TScore = class(TFreeText)
public
  constructor Create(aLayerIndex: integer=-1);
end;

implementation

{ TScore }

constructor TScore.Create(aLayerIndex: integer);
begin
  inherited Create(FScene);
  if aLayerIndex <> -1 then
    FScene.Add(Self, aLayerIndex);
  Caption := '00';
  TexturedFont := texturedfontText;


end;

end.
