{
  File generated by GameHelper, tool provided with OGLCScene library.

  DON'T EDIT THIS UNIT because it may be overwritten by the tool -> your code will be lost !
  Instead, in another unit add "u_sprite_presentation" in the uses clause
  and add your code in a class inherited from TPresentation.

  Usage:
    - add the sprite textures to your atlas with class method TPresentation.LoadTexture().
    - create an instance of the sprite
      i.e. FPresentation := TCustomPresentation.Create(aLAYER_INDEX);
    or if the sprite is a child of another:
           FPresentation := TCustomPresentation.Create(-1);
           FPresentation.SetChildOf(parentSprite, zordervalue);
    - initialize the sprite coordinates
           FPresentation.Setcoordinates(...);
}

unit u_sprite_presentation;

{$mode ObjFPC}{$H+}

interface

uses
  Classes, SysUtils,
  OGLCScene, BGRABitmap, BGRABitmapTypes, u_common;

type

TPresentation = class(TSpriteContainer)
private
  class var texGhostBody, texTile37, texTile38, texGhostEyeLeft, texPacManFull, 
  texGhostMouthEye: PTexture;
  class var FAdditionnalScale: single;
public
  FreeText1: TFreeText;
  FreeText2: TFreeText;
  FreeText3: TFreeText;
  FreeText4: TFreeText;
  FreeText5: TFreeText;
  FreeText6: TFreeText;
  FreeText7: TFreeText;
  FreeText8: TFreeText;
  FreeText9: TFreeText;
  Dot: TSprite;
  FreeText10: TFreeText;
  SuperDot1: TSprite;
  FreeText12: TFreeText;
  Ghost1: TSprite;
  Ghost1Eye: TSprite;
  Ghost2: TSprite;
  Ghost2Eye: TSprite;
  Ghost3: TSprite;
  Ghost3Eye: TSprite;
  Ghost4: TSprite;
  Ghost4Eye: TSprite;
  Blinky: TSprite;
  GhostEyeLeft: TSprite;
  Pinky: TSprite;
  GhostEyeLeft1: TSprite;
  Inky: TSprite;
  GhostEyeLeft2: TSprite;
  Clyde: TSprite;
  GhostEyeLeft3: TSprite;
  PacMan: TSprite;
  SuperDot2: TSprite;
  GhostMouthEye: TSprite;
  GhostMouthEye1: TSprite;
  GhostMouthEye2: TSprite;
  GhostMouthEye3: TSprite;
  LabelBonus: TFreeText;
  class procedure LoadTexture(aAtlas: TOGLCTextureAtlas);
  constructor Create(aLayerIndex: integer=-1);
end;

implementation

{ TPresentation }

class procedure TPresentation.LoadTexture(aAtlas: TOGLCTextureAtlas);
var texFolder: string;
begin
  FAdditionnalScale := AdditionnalScale;
  texFolder := u_common.TexturesFolder;
  texGhostBody := aAtlas.AddMultiFrameImageFromSVG(texFolder+'GhostBody.svg', ScaleW(64)*2, ScaleH(64)*1, 2, 1);
  texTile37 := aAtlas.AddFromSVG(texFolder+'Tile37.svg', ScaleW(32), ScaleH(32));
  texTile38 := aAtlas.AddFromSVG(texFolder+'Tile38.svg', ScaleW(32), ScaleH(32));
  texGhostEyeLeft := aAtlas.AddFromSVG(texFolder+'GhostEyeLeft.svg', ScaleW(39), ScaleH(19));
  texPacManFull := aAtlas.AddMultiFrameImageFromSVG(texFolder+'PacManFull.svg', ScaleW(64)*14, ScaleH(64)*1, 14, 1);
  texGhostMouthEye := aAtlas.AddFromSVG(texFolder+'GhostMouthEye.svg', ScaleW(46), ScaleH(24));
end;

constructor TPresentation.Create(aLayerIndex: integer);
begin
  inherited Create(FScene);
  if aLayerIndex <> -1 then
    FScene.Add(Self, aLayerIndex);

  FreeText1 := TFreeText.Create(FScene);
  with FreeText1 do begin
    SetChildOf(Self, 0);
    Caption := 'CHARACTER   /   NICKNAME';
    TexturedFont := texturedfontText;
    SetCoordinate(1.033*FreeText1.Width, 0.052*FreeText1.Height);
  end;

  FreeText2 := TFreeText.Create(FScene);
  with FreeText2 do begin
    SetChildOf(Self, 0);
    Tint.Value := BGRA(255,0,0);
    Caption := '-SHADOW';
    TexturedFont := texturedfontText;
    SetCoordinate(2.965*FreeText2.Width, 2.271*FreeText2.Height);
  end;

  FreeText3 := TFreeText.Create(FScene);
  with FreeText3 do begin
    SetChildOf(Self, 0);
    Tint.Value := BGRA(255,0,0);
    Caption := '"BLINKY"';
    TexturedFont := texturedfontText;
    SetCoordinate(3.856*FreeText3.Width, 2.271*FreeText3.Height);
  end;

  FreeText4 := TFreeText.Create(FScene);
  with FreeText4 do begin
    SetChildOf(Self, 0);
    Tint.Value := BGRA(255,184,255);
    Caption := '-SPEEDY';
    TexturedFont := texturedfontText;
    SetCoordinate(3.194*FreeText4.Width, 4.771*FreeText4.Height);
  end;

  FreeText5 := TFreeText.Create(FScene);
  with FreeText5 do begin
    SetChildOf(Self, 0);
    Tint.Value := BGRA(255,184,255);
    Caption := '"PINKY"';
    TexturedFont := texturedfontText;
    SetCoordinate(4.449*FreeText5.Width, 4.771*FreeText5.Height);
  end;

  FreeText6 := TFreeText.Create(FScene);
  with FreeText6 do begin
    SetChildOf(Self, 0);
    Tint.Value := BGRA(0,255,255);
    Caption := '-BASHFUL';
    TexturedFont := texturedfontText;
    SetCoordinate(2.702*FreeText6.Width, 7.271*FreeText6.Height);
  end;

  FreeText7 := TFreeText.Create(FScene);
  with FreeText7 do begin
    SetChildOf(Self, 0);
    Tint.Value := BGRA(0,255,255);
    Caption := '"INKY"';
    TexturedFont := texturedfontText;
    SetCoordinate(5.205*FreeText7.Width, 7.271*FreeText7.Height);
  end;

  FreeText8 := TFreeText.Create(FScene);
  with FreeText8 do begin
    SetChildOf(Self, 0);
    Tint.Value := BGRA(255,184,81);
    Caption := '-POKEY';
    TexturedFont := texturedfontText;
    SetCoordinate(3.659*FreeText8.Width, 9.771*FreeText8.Height);
  end;

  FreeText9 := TFreeText.Create(FScene);
  with FreeText9 do begin
    SetChildOf(Self, 0);
    Tint.Value := BGRA(255,184,81);
    Caption := '"CLYDE"';
    TexturedFont := texturedfontText;
    SetCoordinate(4.526*FreeText9.Width, 9.771*FreeText9.Height);
  end;

  Dot := TSprite.Create(texTile38, False);
  with Dot do begin
    SetChildOf(Self, 0);
    Frame := 1.0;
    SetSize(ScaleW(Round(32*FAdditionnalScale)), ScaleH(Round(32*FAdditionnalScale)));
    SetCoordinate(12.168*Dot.Width, 16.760*Dot.Height);
  end;

  FreeText10 := TFreeText.Create(FScene);
  with FreeText10 do begin
    SetChildOf(Self, 0);
    Caption := '10 pts';
    TexturedFont := texturedfontText;
    SetCoordinate(5.007*FreeText10.Width, 16.760*FreeText10.Height);
  end;

  SuperDot1 := TSprite.Create(texTile37, False);
  with SuperDot1 do begin
    SetChildOf(Self, 0);
    Frame := 1.0;
    SetSize(ScaleW(Round(32*FAdditionnalScale)), ScaleH(Round(32*FAdditionnalScale)));
    SetCoordinate(12.168*SuperDot1.Width, 18.422*SuperDot1.Height);
  end;

  FreeText12 := TFreeText.Create(FScene);
  with FreeText12 do begin
    SetChildOf(Self, 0);
    Caption := '50 pts';
    TexturedFont := texturedfontText;
    SetCoordinate(4.950*FreeText12.Width, 18.422*FreeText12.Height);
  end;

  Ghost1 := TSprite.Create(texGhostBody, False);
  with Ghost1 do begin
    SetChildOf(Self, 0);
    Frame := 1.0;
    SetSize(ScaleW(Round(64*FAdditionnalScale)), ScaleH(Round(64*FAdditionnalScale)));
    SetCoordinate(3.906*Ghost1.Width, 0.885*Ghost1.Height);
  end;

  Ghost1Eye := TSprite.Create(texGhostEyeLeft, False);
  with Ghost1Eye do begin
    SetChildOf(Ghost1, 0);
    FlipH := True;
    Frame := 1.0;
    SetSize(ScaleW(Round(39*FAdditionnalScale)), ScaleH(Round(19*FAdditionnalScale)));
    SetCoordinate(0.266*Ghost1.Width, 0.203*Ghost1.Height);
  end;

  Ghost2 := TSprite.Create(texGhostBody, False);
  with Ghost2 do begin
    SetChildOf(Self, 0);
    Tint.Value := BGRA(255,184,255);
    Frame := 1.0;
    SetSize(ScaleW(Round(64*FAdditionnalScale)), ScaleH(Round(64*FAdditionnalScale)));
    SetCoordinate(3.906*Ghost2.Width, 2.135*Ghost2.Height);
  end;

  Ghost2Eye := TSprite.Create(texGhostEyeLeft, False);
  with Ghost2Eye do begin
    SetChildOf(Ghost2, 0);
    FlipH := True;
    Frame := 1.0;
    SetSize(ScaleW(Round(39*FAdditionnalScale)), ScaleH(Round(19*FAdditionnalScale)));
    SetCoordinate(0.266*Ghost2.Width, 0.203*Ghost2.Height);
  end;

  Ghost3 := TSprite.Create(texGhostBody, False);
  with Ghost3 do begin
    SetChildOf(Self, 0);
    Tint.Value := BGRA(0,255,255);
    Frame := 1.0;
    SetSize(ScaleW(Round(64*FAdditionnalScale)), ScaleH(Round(64*FAdditionnalScale)));
    SetCoordinate(3.906*Ghost3.Width, 3.385*Ghost3.Height);
  end;

  Ghost3Eye := TSprite.Create(texGhostEyeLeft, False);
  with Ghost3Eye do begin
    SetChildOf(Ghost3, 0);
    FlipH := True;
    Frame := 1.0;
    SetSize(ScaleW(Round(39*FAdditionnalScale)), ScaleH(Round(19*FAdditionnalScale)));
    SetCoordinate(0.266*Ghost3.Width, 0.203*Ghost3.Height);
  end;

  Ghost4 := TSprite.Create(texGhostBody, False);
  with Ghost4 do begin
    SetChildOf(Self, 0);
    Tint.Value := BGRA(255,184,81);
    Frame := 1.0;
    SetSize(ScaleW(Round(64*FAdditionnalScale)), ScaleH(Round(64*FAdditionnalScale)));
    SetCoordinate(3.906*Ghost4.Width, 4.635*Ghost4.Height);
  end;

  Ghost4Eye := TSprite.Create(texGhostEyeLeft, False);
  with Ghost4Eye do begin
    SetChildOf(Ghost4, 0);
    FlipH := True;
    Frame := 1.0;
    SetSize(ScaleW(Round(39*FAdditionnalScale)), ScaleH(Round(19*FAdditionnalScale)));
    SetCoordinate(0.266*Ghost4.Width, 0.203*Ghost4.Height);
  end;

  Blinky := TSprite.Create(texGhostBody, False);
  with Blinky do begin
    SetChildOf(Self, 0);
    Frame := 1.0;
    SetSize(ScaleW(Round(64*FAdditionnalScale)), ScaleH(Round(64*FAdditionnalScale)));
    SetCoordinate(16.406*Blinky.Width, 6.507*Blinky.Height);
  end;

  GhostEyeLeft := TSprite.Create(texGhostEyeLeft, False);
  with GhostEyeLeft do begin
    SetChildOf(Blinky, 0);
    Frame := 1.0;
    SetSize(ScaleW(Round(39*FAdditionnalScale)), ScaleH(Round(19*FAdditionnalScale)));
    SetCoordinate(0.109*Blinky.Width, 0.203*Blinky.Height);
  end;

  Pinky := TSprite.Create(texGhostBody, False);
  with Pinky do begin
    SetChildOf(Self, 0);
    Tint.Value := BGRA(255,184,255);
    Frame := 1.0;
    SetSize(ScaleW(Round(64*FAdditionnalScale)), ScaleH(Round(64*FAdditionnalScale)));
    SetCoordinate(17.406*Pinky.Width, 6.507*Pinky.Height);
  end;

  GhostEyeLeft1 := TSprite.Create(texGhostEyeLeft, False);
  with GhostEyeLeft1 do begin
    SetChildOf(Pinky, 0);
    Frame := 1.0;
    SetSize(ScaleW(Round(39*FAdditionnalScale)), ScaleH(Round(19*FAdditionnalScale)));
    SetCoordinate(0.109*Pinky.Width, 0.203*Pinky.Height);
  end;

  Inky := TSprite.Create(texGhostBody, False);
  with Inky do begin
    SetChildOf(Self, 0);
    Tint.Value := BGRA(0,255,255);
    Frame := 1.0;
    SetSize(ScaleW(Round(64*FAdditionnalScale)), ScaleH(Round(64*FAdditionnalScale)));
    SetCoordinate(18.406*Inky.Width, 6.507*Inky.Height);
  end;

  GhostEyeLeft2 := TSprite.Create(texGhostEyeLeft, False);
  with GhostEyeLeft2 do begin
    SetChildOf(Inky, 0);
    Frame := 1.0;
    SetSize(ScaleW(Round(39*FAdditionnalScale)), ScaleH(Round(19*FAdditionnalScale)));
    SetCoordinate(0.109*Inky.Width, 0.203*Inky.Height);
  end;

  Clyde := TSprite.Create(texGhostBody, False);
  with Clyde do begin
    SetChildOf(Self, 0);
    Tint.Value := BGRA(255,184,81);
    Frame := 1.0;
    SetSize(ScaleW(Round(64*FAdditionnalScale)), ScaleH(Round(64*FAdditionnalScale)));
    SetCoordinate(19.406*Clyde.Width, 6.507*Clyde.Height);
  end;

  GhostEyeLeft3 := TSprite.Create(texGhostEyeLeft, False);
  with GhostEyeLeft3 do begin
    SetChildOf(Clyde, 0);
    Frame := 1.0;
    SetSize(ScaleW(Round(39*FAdditionnalScale)), ScaleH(Round(19*FAdditionnalScale)));
    SetCoordinate(0.109*Clyde.Width, 0.203*Clyde.Height);
  end;

  PacMan := TSprite.Create(texPacManFull, False);
  with PacMan do begin
    SetChildOf(Self, 0);
    FlipH := True;
    Frame := 1.0;
    SetSize(ScaleW(Round(64*FAdditionnalScale)), ScaleH(Round(64*FAdditionnalScale)));
    SetCoordinate(14.063*PacMan.Width, 6.507*PacMan.Height);
  end;

  SuperDot2 := TSprite.Create(texTile37, False);
  with SuperDot2 do begin
    SetChildOf(Self, 0);
    Frame := 1.0;
    SetSize(ScaleW(Round(32*FAdditionnalScale)), ScaleH(Round(32*FAdditionnalScale)));
    SetCoordinate(7.813*SuperDot2.Width, 13.645*SuperDot2.Height);
  end;

  GhostMouthEye := TSprite.Create(texGhostMouthEye, False);
  with GhostMouthEye do begin
    SetChildOf(Blinky, 1);
    Frame := 1.0;
    SetSize(ScaleW(Round(46*FAdditionnalScale)), ScaleH(Round(24*FAdditionnalScale)));
    SetCoordinate(0.141*Blinky.Width, 0.344*Blinky.Height);
  end;

  GhostMouthEye1 := TSprite.Create(texGhostMouthEye, False);
  with GhostMouthEye1 do begin
    SetChildOf(Pinky, 1);
    Frame := 1.0;
    SetSize(ScaleW(Round(46*FAdditionnalScale)), ScaleH(Round(24*FAdditionnalScale)));
    SetCoordinate(0.141*Pinky.Width, 0.344*Pinky.Height);
  end;

  GhostMouthEye2 := TSprite.Create(texGhostMouthEye, False);
  with GhostMouthEye2 do begin
    SetChildOf(Inky, 1);
    Frame := 1.0;
    SetSize(ScaleW(Round(46*FAdditionnalScale)), ScaleH(Round(24*FAdditionnalScale)));
    SetCoordinate(0.141*Inky.Width, 0.344*Inky.Height);
  end;

  GhostMouthEye3 := TSprite.Create(texGhostMouthEye, False);
  with GhostMouthEye3 do begin
    SetChildOf(Clyde, 1);
    Frame := 1.0;
    SetSize(ScaleW(Round(46*FAdditionnalScale)), ScaleH(Round(24*FAdditionnalScale)));
    SetCoordinate(0.141*Clyde.Width, 0.344*Clyde.Height);
  end;

  LabelBonus := TFreeText.Create(FScene);
  with LabelBonus do begin
    SetChildOf(Self, 0);
    Tint.Value := BGRA(0,255,255);
    Caption := '1600';
    TexturedFont := texturedfontBonus;
    SetCoordinate(6.817*LabelBonus.Width, 14.448*LabelBonus.Height);
  end;

end;

end.
