{
  File generated by GameHelper, tool provided with OGLCScene library.

  DON'T EDIT THIS UNIT because it may be overwritten by the tool -> your code will be lost !
  Instead, in another unit add "u_sprite_baseghost" in the uses clause
  and add your code in a class inherited from TBaseGhost.

  Usage:
    - add the sprite textures to your atlas with class method TBaseGhost.LoadTexture().
    - create an instance of the sprite
      i.e. FBaseGhost := TCustomBaseGhost.Create(aLAYER_INDEX);
    or if the sprite is a child of another:
           FBaseGhost := TCustomBaseGhost.Create(-1);
           FBaseGhost.SetChildOf(parentSprite, zordervalue);
    - initialize the sprite coordinates
           FBaseGhost.Setcoordinates(...);
}

unit u_sprite_baseghost;

{$mode ObjFPC}{$H+}

interface

uses
  Classes, SysUtils,
  OGLCScene, BGRABitmap, BGRABitmapTypes, u_common;

type

TBaseGhost = class(TSprite)
private
  class var texGhostBody: PTexture;
  class var FAdditionnalScale: single;
public
  class procedure LoadTexture(aAtlas: TOGLCTextureAtlas);
  constructor Create(aLayerIndex: integer=-1);
end;

implementation

{ TBaseGhost }

class procedure TBaseGhost.LoadTexture(aAtlas: TOGLCTextureAtlas);
var texFolder: string;
begin
  FAdditionnalScale := AdditionnalScale;
  texFolder := u_common.TexturesFolder;
  texGhostBody := aAtlas.AddMultiFrameImageFromSVG(texFolder+'GhostBody.svg', ScaleW(64)*2, ScaleH(64)*1, 2, 1);
end;

constructor TBaseGhost.Create(aLayerIndex: integer);
begin
  inherited Create(texGhostBody, False);
  if aLayerIndex <> -1 then
    FScene.Add(Self, aLayerIndex);
  SetSize(ScaleW(Round(64*FAdditionnalScale)), ScaleH(Round(64*FAdditionnalScale)));


end;

end.
