{
  File generated by GameHelper, tool provided with OGLCScene library.

  DON'T EDIT THIS UNIT because it may be overwritten by the tool -> your code will be lost !
  Instead, in another unit add "u_sprite_labelgameover" in the uses clause
  and add your code in a class inherited from TLabelGameOver.

  Usage:
    - create an instance of the sprite
      i.e. FLabelGameOver := TCustomLabelGameOver.Create(aLAYER_INDEX);
    or if the sprite is a child of another:
           FLabelGameOver := TCustomLabelGameOver.Create(-1);
           FLabelGameOver.SetChildOf(parentSprite, zordervalue);
    - initialize the sprite coordinates
           FLabelGameOver.Setcoordinates(...);
}

unit u_sprite_labelgameover;

{$mode ObjFPC}{$H+}

interface

uses
  Classes, SysUtils,
  OGLCScene, BGRABitmap, BGRABitmapTypes, u_common;

type

TLabelGameOver = class(TFreeText)
public
  constructor Create(aLayerIndex: integer=-1);
end;

implementation

{ TLabelGameOver }

constructor TLabelGameOver.Create(aLayerIndex: integer);
begin
  inherited Create(FScene);
  if aLayerIndex <> -1 then
    FScene.Add(Self, aLayerIndex);
  SetCoordinate(ScaleWF(43.38), ScaleHF(8.84));
  Scale.Value := PointF(1.55, 1.55);
  Tint.Value := BGRA(255,0,0);
  Caption := 'GAME   OVER';
  TexturedFont := texturedfontText;


end;

end.
