{
  File generated by GameHelper, tool provided with OGLCScene library.

  DON'T EDIT THIS UNIT because it may be overwritten by the tool -> your code will be lost !
  Instead, in another unit add "u_sprite_basehighscore" in the uses clause
  and add your code in a class inherited from TBaseHighScore.

  Usage:
    - create an instance of the sprite
      i.e. FHighScore := TCustomHighScore.Create(aLAYER_INDEX);
    or if the sprite is a child of another:
           FHighScore := TCustomHighScore.Create(-1);
           FHighScore.SetChildOf(parentSprite, zordervalue);
    - initialize the sprite coordinates
           FHighScore.Setcoordinates(...);
}

unit u_sprite_basehighscore;

{$mode ObjFPC}{$H+}

interface

uses
  Classes, SysUtils,
  OGLCScene, BGRABitmap, BGRABitmapTypes, u_common;

type

TBaseHighScore = class(TFreeText)
public
  constructor Create(aLayerIndex: integer=-1);
end;

implementation

{ TBaseHighScore }

constructor TBaseHighScore.Create(aLayerIndex: integer);
begin
  inherited Create(FScene);
  if aLayerIndex <> -1 then
    FScene.Add(Self, aLayerIndex);
  Caption := '00';
  TexturedFont := texturedfontText;


end;

end.
