{
  File generated by GameHelper, tool provided with OGLCScene library.

  DON'T EDIT THIS UNIT because it may be overwritten by the tool -> your code will be lost !
  Instead, in another unit add "u_sprite_basepacman" in the uses clause
  and add your code in a class inherited from TBasePacMan.

  Usage:
    - add the sprite textures to your atlas with class method TBasePacMan.LoadTexture().
    - create an instance of the sprite
      i.e. FBasePacMan := TCustomBasePacMan.Create(aLAYER_INDEX);
    or if the sprite is a child of another:
           FBasePacMan := TCustomBasePacMan.Create(-1);
           FBasePacMan.SetChildOf(parentSprite, zordervalue);
    - initialize the sprite coordinates
           FBasePacMan.Setcoordinates(...);
}

unit u_sprite_basepacman;

{$mode ObjFPC}{$H+}

interface

uses
  Classes, SysUtils,
  OGLCScene, BGRABitmap, BGRABitmapTypes, u_common;

type

TBasePacMan = class(TSprite)
private
  class var texPacManFull: PTexture;
  class var FAdditionnalScale: single;
public
  class procedure LoadTexture(aAtlas: TOGLCTextureAtlas);
  constructor Create(aLayerIndex: integer=-1);
end;

implementation

{ TBasePacMan }

class procedure TBasePacMan.LoadTexture(aAtlas: TOGLCTextureAtlas);
var texFolder: string;
begin
  FAdditionnalScale := AdditionnalScale;
  texFolder := u_common.TexturesFolder;
  texPacManFull := aAtlas.AddMultiFrameImageFromSVG(texFolder+'PacManFull.svg', ScaleW(64)*14, ScaleH(64)*1, 14, 1);
end;

constructor TBasePacMan.Create(aLayerIndex: integer);
begin
  inherited Create(texPacManFull, False);
  if aLayerIndex <> -1 then
    FScene.Add(Self, aLayerIndex);
  SetSize(ScaleW(Round(64*FAdditionnalScale)), ScaleH(Round(64*FAdditionnalScale)));


end;

end.
